### ISSUE TITLE
using "inview_change" (from the lazy load example) didn't work for me after updating.

### ISSUE THREAD

**Issue by thomastraum** [svelte-inview/svelte-inview#41]
I went back to "on:change" event and it worked again.

Great library thank you!

**Comment by maciekgrzybek** [comment]
Thanks @thomastraum :) `inview_change` should work as well 🤔 Can you provide a repro of your case?

**Comment by jhubbardsf** [comment]
This seems stale and nobody else has commented in over a year so I'm gonna close this. If anyone else comes across this issue, comment and I'll reopen it. But a minimum reproducible repo, as @maciekgrzybek said, would be very helpful.
