### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by J4gQBqqR** [svelte-inview/svelte-inview#49]
Event syntax like `on:inview_change` is not supported in svelte 5 anymore.

**Comment by maciekgrzybek** [comment]
Is svelte 5 even released yet? Seems like it's not 🤔

**Comment by J4gQBqqR** [comment]
I guess it wouldn't hurt to bring the umbrella before it rains? 😉

**Comment by maciekgrzybek** [comment]
Yeah sure thing :) I was just afraid that I missed it :) Not sure if I'll find the time soon... Are you interested in doing this? :)

**Comment by J4gQBqqR** [comment]
```html
<script lang="ts">
	import {
		inview,
		type Options,
		type ObserverEventDetails,
	} from "svelte-inview";

	let isInView: boolean = $state(false);
	const options: Options = { rootMargin: "-100px" };
</script>

<div
	use:inview={options}
	oninview_change={(event: CustomEvent<ObserverEventDetails>) => {
		const { inView, entry, scrollDirection, observer, node } = event.detail;
		isInView = inView;
	}}
	oninview_enter={(event: CustomEvent<ObserverEventDetails>) => {
		const { inView, entry, scrollDirection, observer, node } = event.detail;
		isInView = inView;
	}}
	oninview_leave={(event: CustomEvent<ObserverEventDetails>) => {
		const { inView, entry, scrollDirection, observer, node } = event.detail;
		isInView = inView;
	}}
	oninview_init={(event: CustomEvent<LifecycleEventDetails>) => {
		const { observer, node } = event.detail;
	}}
>
	{isInView ? "Hey I am in the viewport" : "Bye, Bye"}
</div>

```

I tested and verified that the above code works in svelte 5. However, there is one caveat:
![图片](https://github.com/maciekgrzybek/svelte-inview/assets/77554817/4df23c8a-68fe-4753-b3d0-85ce3287c73d)
Not sure this VS Code prompt is coming from svelte 5's incomplete language tool or this library's incompatible type definition between svelte 5.

**Comment by jhubbardsf** [comment]
I believe this should fix the issue with Svelte5

https://github.com/maciekgrzybek/svelte-inview/pull/50

**Comment by travisdmathis** [comment]
can confirm this works after audit fixes for vulnerabilities..

https://github.com/travisdmathis/svelte-5-inview -- deployed and tested because I couldn't wait around for a merge.

```
npm install svelte-5-inview
```

will kill this package once you merge and update.

**Comment by maciekgrzybek** [comment]
Hey folks, sorry for lack of response, I had busy period.... I'll try to merge the update this week 👌

**Comment by matteocontrini** [comment]
Is there a particular reason why the naming convention used here is a mix of styles?

I would expect the handler methods to be called something like `onInviewChange`, instead of the (IMO weird) `oninview_change`.

Btw, thanks everyone for the efforts :)

**Comment by jhubbardsf** [comment]
> Is there a particular reason why the naming convention used here is a mix of styles?
> 
> I would expect the handler methods to be called something like `onInviewChange`, instead of the (IMO weird) `oninview_change`.
> 
> Btw, thanks everyone for the efforts :)

This is just the new Svelte 5 event handler naming syntax ([link](https://svelte-5-preview.vercel.app/docs/event-handlers))

**Comment by maciekgrzybek** [comment]
Hey folks, thanks for all the work you did here and sorry for the delay. I've just merged the changes you did for the v5. Unfortunately in future, I'm afraid I won't have time to properly handle that package :( Does anyone want to become a co-owner?

**Comment by jhubbardsf** [comment]
@maciekgrzybek I’d be happy to help keep up with this repo if you wanted to make my co-owner. I used it in my portfolio website years ago and thought it was a cool library. I’d love to pay it forward by helping keep it up and have the bandwidth.

**Comment by maciekgrzybek** [comment]
Great to here that @jhubbardsf :) let my try an add you :)

**Comment by maciekgrzybek** [comment]
Added, see if it works :)

**Comment by maciekgrzybek** [comment]
@travisdmathis adding you as well in that case :) thanks :)

**Comment by travisdmathis** [comment]
@jhubbardsf I have tested this PR in production thoroughly in Svelte 5 and unless you have any changes you want to make I think it is good to go.

**Comment by maciekgrzybek** [comment]
@travisdmathis I've actually merged the change already, just not from this branch as GH was giving me hard time ;(

**Comment by jhubbardsf** [comment]
@maciekgrzybek Haha, no problem. I accepted the invite you sent though so I can help keep the project up-to-date/alive when you're busy. Happy to help!

**Comment by maciekgrzybek** [comment]
Awesome :)

**Comment by jhubbardsf** [comment]
@matteocontrini It should be backwards compatible and work with svelte 4 or 5. I'll take a look at it locally and get back to you.

**Comment by jhubbardsf** [comment]
@matteocontrini I misread what you wrote. You're absolutely right. I'll get a PR in for that tonight and update you.

**Comment by jhubbardsf** [comment]
@matteocontrini Got the PR in. Once we get it merged that error should go away. Although as far as I'm aware you really can just do an `npm install --force` and ignore it for now. But the actual fix should be in shortly.

PR: #51

**Comment by matteocontrini** [comment]
Thanks. Installing from the branch works.

I think you can simplify the version range with `3 - 5` or `>= 3 < 6`, if I'm reading [the docs](https://github.com/npm/node-semver?tab=readme-ov-file#hyphen-ranges-xyz---abc) correctly.

**Comment by Benanna2019** [comment]
Also just jumping in to say I'm looking forward to the svelte 5 release! It's currently breaking deployment due to mismatched svelte dependencies so excited to get an app deployed 🙏

**Comment by jhubbardsf** [comment]
@Benanna2019 @Devr-pro We're trying to fix the process so I can push PRs through quicker :/. I do believe if do a `npm i --force` or `npm --legacy-peer-deps` it'll install fine (just give a warning instead of an error) but I'll need to test that later today. Hopefully we 4.0.4 released today either way.

@matteocontrini Cool idea! `3-5` would't work because Svelte is in prerelease and `5.0.0-next.X` is different than regular 5. I just wrote it my way to be ore explicit. Although `>=3 < 6` could work you lose some granularity an the "why" becomes less clear (in my opinion).

**Comment by jhubbardsf** [comment]
@matteocontrini @Devr-pro @Benanna2019 

Version 4.0.4 was just published, it should fix the Svelte5 `npm i` errors you guys were seeing.

@Benanna2019 I actually like your `>=3 < 6` approach since it'll future proof any RCs they use along the way. Might add that in a little later since I'm a little busy right now. But you're welcome to create a PR for it as well.

**Comment by matteocontrini** [comment]
I confirm it works, thanks!

**Comment by Benanna2019** [comment]
It works! Thank you so much!
